emc_on_hud=false # Display current EMC on HUD (top left corner) [default: false]
private_emc=false # Should each player have their own EMC storage? [default: false]
creative_items=false # Should creative items have EMC? [default: false]
difficulty=easy # easy | normal | hard - Changes crafting recipe for Dissolver block. [default: hard]
mode=default # default | skyblock - Changes some EMC values. [default: default]
# This only tracks things that are needed to keep the mod going. As you are able to turn these off, we ask that you don't, as it gives us the motivation to keep going :)
analytics_enabled=true # Send anonymous analytics and error reports. [default: true]
