name = "Drakonix One Block Shop"
author = "Henry Post,meltingscales"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e55d0b96fad46fc2773eb027eca47d7740b304e6238f185d76ac67ca742b717a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
