name = "Drakonix One Block Shop"
author = "Henry Post,meltingscales"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "606e5f46611373186adcc49cb0692969a676a709f7f11486f9c1cabbfb980050"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
