name = "Drakonix One Block Shop"
author = "Henry Post,meltingscales"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a4ca32ae37bd64ff6e6bbe018c6a028feef7d358ba9e18442458219a4c8be5f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"
